### PR TITLE
implement find-help page

### PR DESCRIPTION
**Pull request by maharris1011**
this implements the find-help page as close as I can get it to the mockup.

### CODE REVIEW

**Comment by maharris1011** [comment]
actually this doesn't pull from airtable yet, but it does list the projects that are live. And the "Submit a Resource" button is not yet live. What should happen when we click "Submit a Resource"?

**Comment by slythr** [comment]
> actually this doesn't pull from airtable yet, but it does list the projects that are live. And the "Submit a Resource" button is not yet live. What should happen when we click "Submit a Resource"?

mailto:hello@cantstopcolumbus.com

Subject: New resource

**Comment by CoreySchnedl** [comment]
mark, do you need me to help resolve the merge conflict here? I think that was the result of my changes to the home page. Let me know if I can help. @maharris1011

**Comment by maharris1011** [comment]
No worries. These merge conflicts are a real pain in the ass. I will resolve it, no big deal. Probably something I did. I think it might be related to using visual studio code to push my commits up to my branch.

**Pull request merged**
